print("\n\n")
frase = input("Ingresa la oracion que quieras: ")
print("Lista de palabras: ", frase.split())
print("Palabras en mayus:")
frase_mayus = frase.upper()
for palabra in frase_mayus.split():
    print(palabra)
palabra = input("Escribe la palabra que quieres contar en la frase: ")
cantpal = frase_mayus.count(palabra.upper())
print("La palabra", palabra, "aparece", cantpal, "veces")
palabraremplazar = input("Que palabra quieres reemplazar? ")
nuevapalabra = input("Por cual palabra la quieres reemplazar? ")
frasemodificada = frase.replace(palabraremplazar, nuevapalabra)
print("Frase modificada:", frasemodificada)